class Selenium::WebDriver::Chromium::Options
  def initialize: (?profile: nil, **Array[untyped]) -> void
                | (?profile: nil, **nil) -> void

  def process_browser_options: (Hash[untyped, untyped]) -> void

  def camelize?: (Symbol) -> bool
               | (String) -> bool
end
