class Selenium::WebDriver::Support::Guards
  def initialize: (RSpec::Core::Example, ?bug_tracker: String, ?conditions: nil) -> void

  def collect_example_guards: () -> Array[untyped]

  def add_condition: (Symbol, ?Symbol) -> void
                   | (Symbol, ?nil) -> void
                   | (Symbol, ?bool) -> void

  def disposition: () -> Array[untyped]

  def skipping_guard: () -> Selenium::WebDriver::Support::Guards::Guard

  def satisfied?: (Selenium::WebDriver::Support::Guards::Guard) -> bool
end
