class Selenium::WebDriver::Remote::Http::Common
  def call: (Symbol, String, Hash[untyped, untyped]) -> Selenium::WebDriver::Remote::Response
          | (Symbol, String, nil) -> Selenium::WebDriver::Remote::Response

  def server_url: () -> URI::HTTP

  def common_headers: () -> Hash[untyped, untyped]

  def create_response: (String, String, String) -> Selenium::WebDriver::Remote::Response
end
