class Selenium::WebDriver::ActionBuilder
  def initialize: (Selenium::WebDriver::Remote::Bridge, ?devices: Array[untyped], ?async: bool, ?duration: Integer) -> void

  def clear_all_actions: () -> Array[untyped]
end
