class Selenium::WebDriver::ChildProcess
  def exited?: () -> bool

  def waitpid2: (Integer, ?Integer) -> nil
              | (Integer, ?Integer) -> Array[untyped]

  def poll_for_exit: (Integer) -> nil

  def self.build: (*String) -> Selenium::WebDriver::ChildProcess

  def initialize: (*String) -> void

  def start: () -> nil

  def io: () -> String
end
