class Selenium::WebDriver::ChildProcess
  def exited?: () -> bool

  def waitpid2: (Integer, ?Integer) -> nil
              | (Integer, ?Integer) -> Array[untyped]

  def poll_for_exit: (Integer) -> nil
end
