class Selenium::WebDriver::Driver
  def get: (String) -> nil

  def navigate: () -> Selenium::WebDriver::Navigation

  def quit: () -> nil

  def self.for: (Symbol, ?Hash[untyped, untyped]) -> Selenium::WebDriver::Chrome::Driver

  def service_url: (Selenium::WebDriver::Chrome::Service) -> URI::HTTP

  def initialize: (?bridge: nil, ?listener: nil, **Hash[untyped, untyped] | URI::HTTP) -> void

  def create_bridge: (caps: Hash[untyped, untyped], url: URI::HTTP, ?http_client: nil) -> Selenium::WebDriver::Remote::Bridge

  def add_extensions: (Symbol) -> Array[untyped]

  def execute_script: (String, *nil) -> void
end
