class Selenium::WebDriver::DriverFinder
  def initialize: (Selenium::WebDriver::Chrome::Options, Selenium::WebDriver::Chrome::Service) -> void

  def browser_path?: () -> bool

  def browser_path: () -> String

  def paths: () -> Hash[untyped, untyped]

  def to_args: () -> Array[untyped]

  def driver_path: () -> String
end
