class Selenium::WebDriver::Element
  def initialize: (Selenium::WebDriver::Remote::Bridge, String) -> void

  def rect: () -> Selenium::WebDriver::Rectangle

  def to_json: (*untyped) -> String

  def as_json: (*untyped) -> Hash[untyped, untyped]
end
