class Selenium::WebDriver::Options
  def self.chrome: (**Array[untyped]) -> Selenium::WebDriver::Chrome::Options
                 | (**nil) -> Selenium::WebDriver::Chrome::Options

  def initialize: (**Array[untyped]) -> void
                | (**nil) -> void

  def as_json: (*untyped) -> Hash[untyped, untyped]

  def process_w3c_options: (Hash[untyped, untyped]) -> Hash[untyped, untyped]

  def w3c?: (Symbol) -> bool

  def generate_as_json: (String, ?camelize_keys: bool) -> String
                      | (Array[untyped], ?camelize_keys: bool) -> Array[untyped]
                      | (Hash[untyped, untyped], ?camelize_keys: bool) -> Hash[untyped, untyped]

  def process_json_hash: (Hash[untyped, untyped], bool) -> Hash[untyped, untyped]

  def convert_json_key: (Symbol, ?camelize: bool) -> String
                      | (String, ?camelize: bool) -> String

  def camel_case: (String) -> String
end

class Selenium::WebDriver::Chrome::Options
  def self.set_capabilities: () -> void

  def browser_name: () -> String

  def browser_version: () -> nil

  def binary: () -> nil

  def proxy: () -> nil

  def binary=: (String) -> String

  def browser_version=: (nil) -> nil
end
