module Selenium::WebDriver::SearchContext
  def find_element: (*Hash[untyped, untyped]) -> Selenium::WebDriver::Element

  def extract_args: (Array[untyped]) -> Array[untyped]

  def self.finders: () -> Hash[untyped, untyped]
end
