class Selenium::WebDriver::SeleniumManager
  def self.binary_paths: (*String) -> Hash[untyped, untyped]

  def self.binary: () -> String

  def self.run: (*String) -> Hash[untyped, untyped]

  def self.execute_command: (*String) -> Array[untyped]

  def self.parse_result_and_log: (String) -> Hash[untyped, untyped]

  def self.validate_command_result: (Array[untyped], Process::Status, Hash[untyped, untyped], String) -> void
end
