class Selenium::WebDriver::ServiceManager
  def stop: () -> void

  def process_exited?: () -> bool

  def stop_server: () -> void

  def connect_to_server: () -> Net::HTTPOK

  def stop_process: () -> nil
end
