class Selenium::WebDriver::Service
  def self.chrome: (**nil) -> Selenium::WebDriver::Chrome::Service

  def initialize: (?path: nil, ?port: nil, ?log: nil, ?args: nil) -> void

  def env_path: () -> nil

  def launch: () -> Selenium::WebDriver::ServiceManager

  def shutdown_supported: () -> bool
end
