class Selenium::WebDriver::SocketLock
  def initialize: (Integer, Integer) -> void

  def locked: () -> nil

  def lock: () -> void

  def current_time: () -> Float

  def can_lock?: () -> bool

  def did_lock?: () -> bool

  def release: () -> nil
end
