class Selenium::WebDriver::SocketPoller
  def initialize: (String, Integer, ?Integer, ?Float) -> void

  def connected?: () -> bool

  def with_timeout: () -> bool

  def current_time: () -> Float

  def listening?: () -> bool

  def socket_writable?: (Socket) -> Socket

  def conn_completed?: (Socket) -> bool
end
