class Selenium::WebDriver::Support::Guards::GuardCondition
  def initialize: (Symbol, ?Symbol) -> void
                | (Symbol, ?bool) -> void

  def satisfied?: (Selenium::WebDriver::Support::Guards::Guard) -> bool
end
