class Selenium::WebDriver::Support::Guards::Guard
  def initialize: (Hash[untyped, untyped], Symbol, ?Selenium::WebDriver::Support::Guards) -> void

  def exclusive?: () -> bool

  def exclude?: () -> bool

  def message: () -> String
end
