module Selenium
  module WebDriver
    module Remote
      class BiDiBridge < Bridge
        @bidi: untyped

        attr_reader bidi: untyped

        def create_session: (Hash[Symbol, String] capabilities) -> BiDi

        def quit: () -> nil

        def close: () -> untyped
      end
    end
  end
end
