class Selenium::WebDriver::Remote::Bridge
  def execute: (Symbol, ?Hash[untyped, untyped], ?Hash[untyped, untyped]) -> nil
             | (Symbol, ?Hash[untyped, untyped], ?nil) -> Hash[untyped, untyped]
             | (Symbol, ?Hash[untyped, untyped], ?nil) -> nil

  def session_id: () -> String

  def quit: () -> nil
end
