class Selenium::WebDriver::Remote::Capabilities
  def self.json_create: (Hash[untyped, untyped]) -> Selenium::WebDriver::Remote::Capabilities

  def initialize: (?Hash[untyped, untyped]) -> void

  def self.process_timeouts: (Selenium::WebDriver::Remote::Capabilities, Hash[untyped, untyped]) -> void

  def implicit_timeout=: (Integer) -> void

  def timeouts: () -> Hash[untyped, untyped]

  def page_load_timeout=: (Integer) -> void

  def script_timeout=: (Integer) -> Integer

  def self.camel_case: (Symbol) -> String

  def []=: (Symbol, String) -> String
         | (Symbol, bool) -> bool

  def merge!: (Hash[untyped, untyped]) -> void

  def []: (Symbol) -> String

  def browser_name: () -> String
end
