# BUILD FILE SYNTAX: STARLARK

SE_VERSION = "4.34.0-nightly202505232017"
ASSEMBLY_VERSION = "4.0.0.0"
SUPPORTED_NET_STANDARD_VERSIONS = ["netstandard2.0"]

SUPPORTED_DEVTOOLS_VERSIONS = [
    "v137",
    "v135",
    "v136",
]

ASSEMBLY_COMPANY = "Selenium Committers"
ASSEMBLY_COPYRIGHT = "Copyright © Software Freedom Conservancy 2023"
ASSEMBLY_INFORMATIONAL_VERSION = SE_VERSION
ASSEMBLY_PRODUCT = "Selenium"
