# BUILD FILE SYNTAX: STARLARK

SE_VERSION = "4.28.0-nightly202411252021"
ASSEMBLY_VERSION = "4.0.0.0"
SUPPORTED_NET_STANDARD_VERSIONS = ["netstandard2.0"]

SUPPORTED_DEVTOOLS_VERSIONS = [
    "v85",
    "v131",
    "v129",
    "v130",
]

ASSEMBLY_COMPANY = "Selenium Committers"
ASSEMBLY_COPYRIGHT = "Copyright © Software Freedom Conservancy 2023"
ASSEMBLY_INFORMATIONAL_VERSION = SE_VERSION
ASSEMBLY_PRODUCT = "Selenium"
