class Selenium::WebDriver::Interactions::InputDevice
  def initialize: (?String) -> void

  def add_action: (Selenium::WebDriver::Interactions::Scroll) -> Array[untyped]

  def encode: () -> Hash[untyped, untyped]

  def clear_actions: () -> Array[untyped]
end
