class Selenium::WebDriver::Interactions::Scroll
  def initialize: (source: Selenium::WebDriver::Interactions::WheelInput, ?origin: Symbol, ?duration: Float, **Integer) -> void

  def assert_source: (Selenium::WebDriver::Interactions::WheelInput) -> nil

  def encode: () -> Hash[untyped, untyped]
end
