module Selenium::WebDriver::WheelActions
  def scroll_by: (Integer, Integer, ?device: nil) -> Selenium::WebDriver::ActionBuilder

  def scroll: (**Integer?) -> Selenium::WebDriver::ActionBuilder

  def default_scroll_duration: () -> Float

  def wheel_input: (?nil) -> Selenium::WebDriver::Interactions::WheelInput
end
