class Selenium::WebDriver::Chrome::Driver
  def initialize: (?options: Selenium::WebDriver::Chrome::Options, ?service: Selenium::WebDriver::Chrome::Service, ?url: nil, **nil) -> void

  def browser: () -> Symbol
end
